### ISSUE TITLE
Question: RDS Integration

### ISSUE THREAD

**Issue by Sreejith2k** [znb/AWS_MISP#1]
Hello,

Thanks for sharing the configuration. Whether we need to do some additional configuration in the MISP platform to talk RDS? I have created everything through GUI and still, my data is getting written into the MISP EC2 instances (EFS volume) than to the RDS instances. Your help is much appreciated

**Comment by znb** [comment]
Hello @Sreejith2k 

I'm afraid I don't handle support for MISP so I can't really help you out here. 
I have a full workload at the moment so my free time is rather limited.

I'd suggest checking in with the MISP projects [Github](https://github.com/MISP) page, they're super helpful.
